### ISSUE TITLE
Voxel RCNN  trainning

### ISSUE THREAD

**Issue by vehxianfish** [dvlab-research/DeepVision3D#3]
Hi, thanks for your excellent work! I want to reproduce the eq_paradigm on voxel rcnn. So how can I train?
In the `eq_paradigm/vxbased_backbone/` directory, I can't see voxel rcnn configuration files.   
Please release it! thanks again

**Comment by tomztyang** [comment]
At [here](https://github.com/dvlab-research/DeepVision3D/blob/master/OpenPCDet/tools/cfgs/kitti_models/eq_paradigm/vxbased_backbone/proposal_grid_rcnn.yaml), thanks.

**Comment by vehxianfish** [comment]
> At [here](https://github.com/dvlab-research/DeepVision3D/blob/master/OpenPCDet/tools/cfgs/kitti_models/eq_paradigm/vxbased_backbone/proposal_grid_rcnn.yaml), thanks.

Thank you for your prompt response！
