### ISSUE TITLE
Question regarding contextual relative positional encoding

### ISSUE THREAD

**Issue by ywyue** [dvlab-research/DeepVision3D#6]
Hi, thanks for your great work and the code! I have several questions regarding the contextual relative positional encoding:

1. I find there are at least two hyperparameters regarding it, one is POINT_CLOUD_RANGE, another one is QUANTIZE_SIZE. I wonder how do you select POINT_CLOUD_RANGE? Is it handcrafted to specific dataset? E.g. for scannet, we need to calculate the minimum xyz and the maximum xyz for each scene and take the extreme over all scenes? How sensitive is the model to this hyperparameter?

2. Have you compared the contextual relative positional encoding with other positional encoding techniques, e.g. the fourier encoding used in 3DETR?

Looking forward to your reply. Thanks in advance!

**Comment by tomztyang** [comment]
Hi, thanks for the interest.

For Q1. POINT_CLOUD_RANGE is used to make sure the relative distance positive. We have published our setting on ScanNet segmentation. Hope it works well on your side. We didn't tune these parameters much.

For Q2. No, we didn't do ablation studies on this.

Regards,
Zetong

**Comment by ywyue** [comment]
Thanks for your reply. Could you elaborate more on the choice/motivation of POINT_CLOUD_RANGE to be [0, 0, 0, 20, 20, 10]? E.g. if I want to train the model on another dataset, how do I decide the POINT_CLOUD_RANGE?
